import os
import sys
import re
from datetime import datetime, timedelta

# Add backend directory to sys.path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import (
    Base, engine, SessionLocal, Food, User, StudentProfile,
    StudentNutritionGoal, Order, OrderItem, init_db
)

FOOD_ITEMS = [
    {
        "item_id": 1,
        "name": "Paneer Kathi Roll",
        "description": "A delicious roll filled with grilled paneer cubes, crisp capsicum, onions, and mint chutney wrapped in a flaky wheat roti.",
        "category": "Roll",
        "price": 75.0,
        "ingredients": "paneer,onion,capsicum,wheat roti,mint chutney,spices",
        "serving_size": "1 roll (220g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "North Indian",
        "tags": "filling,protein-rich,spicy,roll,high-protein,snack",
        "image_emoji": "🌯",
        "calories": 340.0, "protein": 18.0, "carbohydrates": 32.0, "fat": 16.0,
        "fiber": 4.0, "sugar": 3.0, "sodium": 520.0
    },
    {
        "item_id": 2,
        "name": "Chicken Tikka Roll",
        "description": "Juicy tandoori chicken tikka tossed with fresh onions and green chutney in a warm wheat paratha.",
        "category": "Roll",
        "price": 85.0,
        "ingredients": "chicken,onion,wheat roti,mint chutney,spices",
        "serving_size": "1 roll (240g)",
        "vegetarian": False, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 9, "available": True, "cuisine": "North Indian",
        "tags": "protein,non-veg,roll,savory,high-protein",
        "image_emoji": "🌯",
        "calories": 380.0, "protein": 26.0, "carbohydrates": 35.0, "fat": 12.0,
        "fiber": 3.0, "sugar": 2.0, "sodium": 640.0
    },
    {
        "item_id": 3,
        "name": "Egg Bhurji Roll",
        "description": "Double egg scramble cooked with chopped tomatoes, onions, green chillies, and roasted cumin.",
        "category": "Roll",
        "price": 55.0,
        "ingredients": "eggs,onion,tomato,wheat roti,green chilli,spices",
        "serving_size": "1 roll (200g)",
        "vegetarian": False, "vegan": False, "jain": False,
        "contains_egg": True, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 7, "available": True, "cuisine": "Indian",
        "tags": "quick-bite,egg,protein,savory",
        "image_emoji": "🌯",
        "calories": 290.0, "protein": 14.0, "carbohydrates": 28.0, "fat": 13.0,
        "fiber": 2.5, "sugar": 2.0, "sodium": 480.0
    },
    {
        "item_id": 4,
        "name": "Aloo Corn Roll",
        "description": "Spiced golden potatoes and sweet corn kernels seasoned with chaat masala in a crispy wrap.",
        "category": "Roll",
        "price": 45.0,
        "ingredients": "potatoes,sweet corn,wheat roti,coriander,spices",
        "serving_size": "1 roll (190g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 6, "available": True, "cuisine": "Indian",
        "tags": "budget,vegan,quick-bite,crispy",
        "image_emoji": "🌯",
        "calories": 260.0, "protein": 6.0, "carbohydrates": 42.0, "fat": 8.0,
        "fiber": 4.5, "sugar": 3.5, "sodium": 410.0
    },
    {
        "item_id": 5,
        "name": "Veg Biryani",
        "description": "Fragrant long-grain basmati rice layered with garden vegetables, saffron, and aromatic spices.",
        "category": "Rice",
        "price": 80.0,
        "ingredients": "basmati rice,carrots,beans,peas,onion,aromatic spices",
        "serving_size": "1 bowl (350g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 14, "available": True, "cuisine": "Hyderabadi",
        "tags": "heavy-meal,filling,flavorful,lunch",
        "image_emoji": "🍚",
        "calories": 450.0, "protein": 10.0, "carbohydrates": 70.0, "fat": 12.0,
        "fiber": 6.0, "sugar": 3.0, "sodium": 590.0
    },
    {
        "item_id": 6,
        "name": "Chicken Dum Biryani",
        "description": "Slow-cooked Hyderabadi chicken biryani infused with kewra water, caramelized onions, and tender bone-in chicken.",
        "category": "Rice",
        "price": 120.0,
        "ingredients": "basmati rice,chicken,yogurt,fried onion,saffron,spices",
        "serving_size": "1 bowl (400g)",
        "vegetarian": False, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 15, "available": True, "cuisine": "Hyderabadi",
        "tags": "hearty,non-veg,chef-special,high-protein",
        "image_emoji": "🍗",
        "calories": 580.0, "protein": 34.0, "carbohydrates": 65.0, "fat": 20.0,
        "fiber": 4.0, "sugar": 2.5, "sodium": 750.0
    },
    {
        "item_id": 7,
        "name": "Rajma Chawal",
        "description": "Home-style tender red kidney beans slow-simmered in rich ginger-tomato gravy, served over steamed basmati rice.",
        "category": "Rice",
        "price": 70.0,
        "ingredients": "kidney beans,basmati rice,tomato gravy,ginger,garlic,spices",
        "serving_size": "1 bowl (380g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 10, "available": True, "cuisine": "Punjabi",
        "tags": "comfort-food,homely,fiber-rich,filling",
        "image_emoji": "🍛",
        "calories": 420.0, "protein": 15.0, "carbohydrates": 74.0, "fat": 6.0,
        "fiber": 11.0, "sugar": 4.0, "sodium": 540.0
    },
    {
        "item_id": 8,
        "name": "Jain Dal Khichdi",
        "description": "Wholesome yellow moong dal and rice tempered with cumin and cow ghee, without onion, garlic, or root vegetables.",
        "category": "Rice",
        "price": 60.0,
        "ingredients": "rice,yellow moong dal,cumin,turmeric,ghee",
        "serving_size": "1 bowl (320g)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "Indian",
        "tags": "light,gut-friendly,jain,comfort,healthy",
        "image_emoji": "🍲",
        "calories": 310.0, "protein": 11.0, "carbohydrates": 52.0, "fat": 6.5,
        "fiber": 5.0, "sugar": 1.0, "sodium": 380.0
    },
    {
        "item_id": 9,
        "name": "Curd Rice",
        "description": "Cooling South Indian comfort rice mixed with velvety curd, tempered with mustard seeds, curry leaves, and ginger.",
        "category": "Rice",
        "price": 50.0,
        "ingredients": "rice,fresh curd,mustard seeds,curry leaves,green chilli",
        "serving_size": "1 bowl (300g)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 5, "available": True, "cuisine": "South Indian",
        "tags": "cooling,soothing,exam-calm,gut-friendly",
        "image_emoji": "🥣",
        "calories": 280.0, "protein": 8.0, "carbohydrates": 44.0, "fat": 7.0,
        "fiber": 2.0, "sugar": 3.0, "sodium": 340.0
    },
    {
        "item_id": 10,
        "name": "Schezwan Fried Rice",
        "description": "Wok-tossed rice with crisp vegetables in spicy, garlicky Schezwan sauce with a hint of toasted sesame.",
        "category": "Rice",
        "price": 75.0,
        "ingredients": "rice,cabbage,bell pepper,onion,schezwan sauce,garlic",
        "serving_size": "1 bowl (330g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 11, "available": True, "cuisine": "Indo-Chinese",
        "tags": "fiery,spicy,street-style,filling",
        "image_emoji": "🥡",
        "calories": 390.0, "protein": 7.0, "carbohydrates": 68.0, "fat": 10.0,
        "fiber": 4.0, "sugar": 3.0, "sodium": 680.0
    },
    {
        "item_id": 11,
        "name": "Cheese Grilled Sandwich",
        "description": "Toasted golden brown bread slices loaded with melted cheddar-mozzarella blend, bell peppers, and oregano.",
        "category": "Snacks",
        "price": 50.0,
        "ingredients": "white bread,cheese slice,tomato,cucumber,capsicum,butter",
        "serving_size": "2 halves (180g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 5, "available": True, "cuisine": "Continental",
        "tags": "cheesy,quick,crowd-favorite,comfort",
        "image_emoji": "🥪",
        "calories": 320.0, "protein": 12.0, "carbohydrates": 36.0, "fat": 14.0,
        "fiber": 3.0, "sugar": 3.0, "sodium": 510.0
    },
    {
        "item_id": 12,
        "name": "Masala Dosa",
        "description": "Golden crisp crepe made from fermented batter, stuffed with mildly spiced potato masala, served with sambar & coconut chutney.",
        "category": "Snacks",
        "price": 60.0,
        "ingredients": "fermented rice-lentil batter,spiced potato filling,coconut chutney,sambar",
        "serving_size": "1 dosa (250g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 10, "available": True, "cuisine": "South Indian",
        "tags": "crispy,traditional,filling,breakfast",
        "image_emoji": "🥞",
        "calories": 340.0, "protein": 8.0, "carbohydrates": 54.0, "fat": 9.0,
        "fiber": 5.0, "sugar": 2.5, "sodium": 490.0
    },
    {
        "item_id": 13,
        "name": "Samosa (2 pcs)",
        "description": "Flaky, golden triangular pastries filled with spicy mashed potatoes, green peas, and whole coriander seeds.",
        "category": "Snacks",
        "price": 25.0,
        "ingredients": "refined flour pastry,spiced potato,peas,cumin,tamarind chutney",
        "serving_size": "2 pieces (160g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 4, "available": True, "cuisine": "North Indian",
        "tags": "budget,crispy,tea-time,street-food",
        "image_emoji": "🥟",
        "calories": 280.0, "protein": 5.0, "carbohydrates": 34.0, "fat": 14.0,
        "fiber": 3.0, "sugar": 2.0, "sodium": 460.0
    },
    {
        "item_id": 14,
        "name": "Mumbai Vada Pav",
        "description": "The quintessential Mumbai burger: batata vada deep-fried in gram flour batter, sandwiched with garlic peanut chutney in a soft pav.",
        "category": "Snacks",
        "price": 25.0,
        "ingredients": "potato patty,pav bun,garlic chutney,fried green chilli",
        "serving_size": "1 pav (150g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": True,
        "spicy": True, "sweet": False,
        "preparation_time": 4, "available": True, "cuisine": "Maharashtrian",
        "tags": "street-style,spicy,grab-and-go,budget",
        "image_emoji": "🍔",
        "calories": 290.0, "protein": 6.0, "carbohydrates": 42.0, "fat": 11.0,
        "fiber": 3.5, "sugar": 3.0, "sodium": 520.0
    },
    {
        "item_id": 15,
        "name": "Veg Cutlet (2 pcs)",
        "description": "Crisp crumb-coated patties made of potatoes, beetroot, green peas, and carrots with spicy mint dip.",
        "category": "Snacks",
        "price": 35.0,
        "ingredients": "potatoes,beetroot,carrots,breadcrumbs,green chutney",
        "serving_size": "2 cutlets (140g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 6, "available": True, "cuisine": "Indian",
        "tags": "crispy,budget,evening-snack",
        "image_emoji": "🧆",
        "calories": 220.0, "protein": 4.5, "carbohydrates": 32.0, "fat": 8.5,
        "fiber": 4.0, "sugar": 3.0, "sodium": 390.0
    },
    {
        "item_id": 16,
        "name": "Bun Maska",
        "description": "Classic Irani bakery-style soft bun generously spread with salted amul butter, perfect alongside cutting chai.",
        "category": "Snacks",
        "price": 25.0,
        "ingredients": "soft bun,butter,tutti frutti",
        "serving_size": "1 bun (110g)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 3, "available": True, "cuisine": "Parsi/Irani",
        "tags": "nostalgic,sweet-touch,tea-partner,comfort",
        "image_emoji": "🍞",
        "calories": 240.0, "protein": 5.0, "carbohydrates": 30.0, "fat": 11.0,
        "fiber": 1.5, "sugar": 5.0, "sodium": 290.0
    },
    {
        "item_id": 17,
        "name": "Indori Poha",
        "description": "Steamed flattened rice tossed with turmeric, mustard seeds, onions, and crunchy peanuts, topped with ratlami sev and fresh lemon juice.",
        "category": "Snacks",
        "price": 30.0,
        "ingredients": "flattened rice,peanuts,onion,mustard seeds,lemon,sev",
        "serving_size": "1 plate (200g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": True,
        "spicy": False, "sweet": False,
        "preparation_time": 5, "available": True, "cuisine": "Central Indian",
        "tags": "light-breakfast,vegan,digestible,quick-bite",
        "image_emoji": "🥣",
        "calories": 250.0, "protein": 6.0, "carbohydrates": 45.0, "fat": 5.0,
        "fiber": 3.0, "sugar": 2.0, "sodium": 310.0
    },
    {
        "item_id": 18,
        "name": "Idli Sambar (2 pcs)",
        "description": "Soft, fluffy steamed rice-lentil idlis served piping hot with vegetable toor dal sambar and fresh coconut chutney.",
        "category": "Snacks",
        "price": 40.0,
        "ingredients": "steamed rice-lentil cakes,toor dal sambar,coconut chutney",
        "serving_size": "2 idlis + sambar (260g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 5, "available": True, "cuisine": "South Indian",
        "tags": "healthy,steamed,oil-free,low-calorie",
        "image_emoji": "⚪",
        "calories": 180.0, "protein": 7.0, "carbohydrates": 36.0, "fat": 1.5,
        "fiber": 4.0, "sugar": 2.0, "sodium": 360.0
    },
    {
        "item_id": 19,
        "name": "Chole Bhature",
        "description": "Spicy Punjabi chickpea curry topped with ginger juliennes and pickled onions, paired with two large fluffy golden bhature.",
        "category": "Snacks",
        "price": 85.0,
        "ingredients": "spiced chickpeas,deep-fried puffed bread,pickled onions",
        "serving_size": "2 bhature + chole (380g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 12, "available": True, "cuisine": "Punjabi",
        "tags": "heavy,indulgent,cheat-meal,filling",
        "image_emoji": "🥘",
        "calories": 620.0, "protein": 17.0, "carbohydrates": 78.0, "fat": 28.0,
        "fiber": 9.0, "sugar": 4.0, "sodium": 820.0
    },
    {
        "item_id": 20,
        "name": "Classic Masala Maggi",
        "description": "The college hostel favorite: 2-minute noodles simmered with diced onions, tomatoes, and extra magic masala.",
        "category": "Noodles",
        "price": 40.0,
        "ingredients": "instant noodles,onion,tomato,peas,maggi masala",
        "serving_size": "1 bowl (220g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 7, "available": True, "cuisine": "Indian Fusion",
        "tags": "late-night-vibe,nostalgic,spicy,comfort",
        "image_emoji": "🍜",
        "calories": 310.0, "protein": 6.5, "carbohydrates": 46.0, "fat": 11.0,
        "fiber": 2.5, "sugar": 2.0, "sodium": 780.0
    },
    {
        "item_id": 21,
        "name": "Cheese Masala Maggi",
        "description": "Steaming masala noodles topped with a double layer of grated cheddar cheese that melts into a creamy sauce.",
        "category": "Noodles",
        "price": 55.0,
        "ingredients": "instant noodles,processed cheese,vegetables,spices",
        "serving_size": "1 bowl (240g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "Indian Fusion",
        "tags": "creamy,cheesy,comforting,indulgent",
        "image_emoji": "🍜",
        "calories": 420.0, "protein": 11.0, "carbohydrates": 48.0, "fat": 19.0,
        "fiber": 2.5, "sugar": 2.5, "sodium": 890.0
    },
    {
        "item_id": 22,
        "name": "Veg Hakka Noodles",
        "description": "Thin Chinese noodles flash-fried in high-heat wok with shredded cabbage, carrots, bell peppers, and light soy sauce.",
        "category": "Noodles",
        "price": 70.0,
        "ingredients": "noodles,cabbage,carrot,capsicum,spring onion,soy sauce",
        "serving_size": "1 bowl (300g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 9, "available": True, "cuisine": "Indo-Chinese",
        "tags": "mild,classic,wok-tossed,chinese",
        "image_emoji": "🥢",
        "calories": 360.0, "protein": 8.0, "carbohydrates": 62.0, "fat": 9.0,
        "fiber": 4.5, "sugar": 3.0, "sodium": 610.0
    },
    {
        "item_id": 23,
        "name": "Egg Hakka Noodles",
        "description": "Savory wok noodles tossed with fluffy scrambled egg ribbons, crispy spring onions, and garlic-pepper seasoning.",
        "category": "Noodles",
        "price": 80.0,
        "ingredients": "noodles,scrambled egg,vegetables,soy sauce,pepper",
        "serving_size": "1 bowl (320g)",
        "vegetarian": False, "vegan": False, "jain": False,
        "contains_egg": True, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 10, "available": True, "cuisine": "Indo-Chinese",
        "tags": "protein,egg,chinese,savory",
        "image_emoji": "🥢",
        "calories": 410.0, "protein": 15.0, "carbohydrates": 60.0, "fat": 12.0,
        "fiber": 4.0, "sugar": 2.5, "sodium": 660.0
    },
    {
        "item_id": 24,
        "name": "Chilli Paneer Dry",
        "description": "Crispy fried cottage cheese cubes tossed in spicy chilli-garlic sauce with crunchy bell peppers and scallions.",
        "category": "Chinese",
        "price": 95.0,
        "ingredients": "paneer cubes,bell pepper,onion,soya sauce,green chillies",
        "serving_size": "1 plate (250g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 10, "available": True, "cuisine": "Indo-Chinese",
        "tags": "starter,appetizer,spicy,tangy,high-protein",
        "image_emoji": "🧆",
        "calories": 370.0, "protein": 17.0, "carbohydrates": 22.0, "fat": 24.0,
        "fiber": 3.0, "sugar": 4.0, "sodium": 710.0
    },
    {
        "item_id": 25,
        "name": "Chilli Chicken Dry",
        "description": "Battered crispy boneless chicken chunks tossed in dark soya glaze, sliced green chillies, and ginger garlic.",
        "category": "Chinese",
        "price": 110.0,
        "ingredients": "boneless chicken,soya sauce,chilli sauce,spring onion",
        "serving_size": "1 plate (260g)",
        "vegetarian": False, "vegan": False, "jain": False,
        "contains_egg": True, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 11, "available": True, "cuisine": "Indo-Chinese",
        "tags": "spicy,non-veg,protein-snack,chef-special",
        "image_emoji": "🍗",
        "calories": 420.0, "protein": 30.0, "carbohydrates": 18.0, "fat": 22.0,
        "fiber": 2.0, "sugar": 3.0, "sodium": 790.0
    },
    {
        "item_id": 26,
        "name": "Cutting Masala Chai",
        "description": "Kadak strong Indian ginger-cardamom tea brewed with buffalo milk, guaranteed to cure exam stress.",
        "category": "Beverages",
        "price": 15.0,
        "ingredients": "brewed black tea,milk,ginger,cardamom,sugar",
        "serving_size": "1 cutting glass (100ml)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 3, "available": True, "cuisine": "Indian",
        "tags": "energy-boost,exam-prep,hot,budget",
        "image_emoji": "☕",
        "calories": 75.0, "protein": 2.0, "carbohydrates": 11.0, "fat": 2.5,
        "fiber": 0.0, "sugar": 9.0, "sodium": 35.0
    },
    {
        "item_id": 27,
        "name": "South Indian Filter Coffee",
        "description": "Authentic chicory-infused decoction blended with steaming frothy milk, served in a traditional dabara set.",
        "category": "Beverages",
        "price": 25.0,
        "ingredients": "freshly brewed chicory coffee,frothed milk,sugar",
        "serving_size": "1 cup (150ml)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 4, "available": True, "cuisine": "South Indian",
        "tags": "caffeine,invigorating,hot",
        "image_emoji": "☕",
        "calories": 95.0, "protein": 3.5, "carbohydrates": 12.0, "fat": 3.5,
        "fiber": 0.0, "sugar": 9.5, "sodium": 45.0
    },
    {
        "item_id": 28,
        "name": "Iced Cold Coffee",
        "description": "Creamy blended cold coffee made with rich espresso, cold milk, chocolate drizzle, and vanilla ice cream scoop.",
        "category": "Beverages",
        "price": 45.0,
        "ingredients": "espresso blend,chilled milk,vanilla ice cream,chocolate syrup",
        "serving_size": "1 tall glass (300ml)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 4, "available": True, "cuisine": "Continental",
        "tags": "refreshing,sweet,chilled,energy",
        "image_emoji": "🧋",
        "calories": 230.0, "protein": 6.0, "carbohydrates": 32.0, "fat": 9.0,
        "fiber": 0.5, "sugar": 28.0, "sodium": 95.0
    },
    {
        "item_id": 29,
        "name": "Fresh Lime Soda (Sweet/Salt)",
        "description": "Refreshing sparkling club soda with freshly squeezed lime juice, mint leaves, rock salt, and cane sugar.",
        "category": "Beverages",
        "price": 30.0,
        "ingredients": "club soda,fresh lemon juice,mint,kala namak,sugar syrup",
        "serving_size": "1 glass (300ml)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 3, "available": True, "cuisine": "Indian",
        "tags": "digestive,thirst-quencher,vegan,cooling",
        "image_emoji": "🍋",
        "calories": 80.0, "protein": 0.0, "carbohydrates": 20.0, "fat": 0.0,
        "fiber": 0.0, "sugar": 18.0, "sodium": 120.0
    },
    {
        "item_id": 30,
        "name": "Alphonso Mango Lassi",
        "description": "Thick, velvety yogurt beverage churned with pure Ratnagiri Alphonso mango pulp and fragrant cardamom.",
        "category": "Beverages",
        "price": 50.0,
        "ingredients": "thick yogurt,mango pulp,cardamom,pistachio garnish",
        "serving_size": "1 kulhad (250ml)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": True,
        "spicy": False, "sweet": True,
        "preparation_time": 4, "available": True, "cuisine": "Indian",
        "tags": "rich,cooling,sweet,creamy,dessert",
        "image_emoji": "🥭",
        "calories": 240.0, "protein": 7.0, "carbohydrates": 38.0, "fat": 6.5,
        "fiber": 1.0, "sugar": 34.0, "sodium": 80.0
    },
    {
        "item_id": 31,
        "name": "Chilled Masala Buttermilk (Chaas)",
        "description": "Traditional light spiced buttermilk churned with toasted cumin, fresh coriander, ginger, and pink Himalayan salt.",
        "category": "Beverages",
        "price": 20.0,
        "ingredients": "curd,water,roasted cumin,coriander,black salt",
        "serving_size": "1 glass (250ml)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 2, "available": True, "cuisine": "Indian",
        "tags": "gut-friendly,cooling,hydrating,low-calorie",
        "image_emoji": "🥛",
        "calories": 60.0, "protein": 3.0, "carbohydrates": 5.0, "fat": 2.0,
        "fiber": 0.0, "sugar": 4.0, "sodium": 220.0
    },
    {
        "item_id": 32,
        "name": "Warm Gulab Jamun (2 pcs)",
        "description": "Melt-in-mouth fried milk dough spheres soaked in hot saffron and rosewater sugar syrup.",
        "category": "Sweets",
        "price": 35.0,
        "ingredients": "milk solids,sugar syrup,rose water,cardamom",
        "serving_size": "2 pcs (120g)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 3, "available": True, "cuisine": "Indian",
        "tags": "sweet-tooth,dessert,warm,treat",
        "image_emoji": "🍮",
        "calories": 290.0, "protein": 4.0, "carbohydrates": 46.0, "fat": 10.0,
        "fiber": 0.5, "sugar": 38.0, "sodium": 65.0
    },
    {
        "item_id": 33,
        "name": "Chocolate Walnut Brownie",
        "description": "Fudgy, decadent dark chocolate brownie studded with crunchy roasted California walnut halves.",
        "category": "Sweets",
        "price": 60.0,
        "ingredients": "cocoa,walnuts,refined flour,dark chocolate",
        "serving_size": "1 slice (100g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": True,
        "spicy": False, "sweet": True,
        "preparation_time": 3, "available": True, "cuisine": "Bakery",
        "tags": "chocolate-craving,sweet,comfort,treat",
        "image_emoji": "🍰",
        "calories": 360.0, "protein": 5.0, "carbohydrates": 44.0, "fat": 18.0,
        "fiber": 3.0, "sugar": 30.0, "sodium": 120.0
    },
    {
        "item_id": 34,
        "name": "Fresh Fruit Custard",
        "description": "Chilled smooth vanilla custard packed with crisp diced seasonal apples, bananas, and ruby pomegranate seeds.",
        "category": "Sweets",
        "price": 40.0,
        "ingredients": "vanilla custard,apple,banana,pomegranate,grapes",
        "serving_size": "1 bowl (200g)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 4, "available": True, "cuisine": "Continental",
        "tags": "fruity,light-sweet,chilled,healthy",
        "image_emoji": "🍨",
        "calories": 190.0, "protein": 4.0, "carbohydrates": 38.0, "fat": 3.0,
        "fiber": 2.5, "sugar": 28.0, "sodium": 70.0
    },
    {
        "item_id": 35,
        "name": "Amritsari Chole Kulche",
        "description": "Tangy Amritsari spiced chickpeas topped with pickled ginger, green chillies, served with 2 soft baked butter kulchas.",
        "category": "Rice",
        "price": 65.0,
        "ingredients": "chickpeas,refined flour kulcha,onion,tomato,amchur,spices",
        "serving_size": "2 kulche + chole (300g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "North Indian",
        "tags": "hearty,spicy,filling,punjabi,lunch",
        "image_emoji": "🫓",
        "calories": 420.0, "protein": 14.0, "carbohydrates": 65.0, "fat": 11.0,
        "fiber": 7.0, "sugar": 4.0, "sodium": 620.0
    },
    {
        "item_id": 36,
        "name": "Mumbai Pav Bhaji",
        "description": "Sizzling spiced mashed potato, tomato, and green pea curry with dollops of melting butter, served with 2 warm toasted pavs.",
        "category": "Snacks",
        "price": 70.0,
        "ingredients": "potatoes,tomatoes,peas,butter,pav,capsicum,pav bhaji masala",
        "serving_size": "2 pav + bhaji (280g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 7, "available": True, "cuisine": "Maharashtrian",
        "tags": "buttery,spicy,street-favorite,hot,snack",
        "image_emoji": "🍲",
        "calories": 460.0, "protein": 9.0, "carbohydrates": 58.0, "fat": 22.0,
        "fiber": 6.0, "sugar": 5.0, "sodium": 680.0
    },
    {
        "item_id": 37,
        "name": "Soya Chaap Tikka Roll",
        "description": "Tandoor-marinated protein-packed soya chaap chunks rolled with sliced onions and spicy mint chutney in a whole wheat wrap.",
        "category": "Roll",
        "price": 75.0,
        "ingredients": "soya chaap,onion,capsicum,wheat roti,mint chutney,tandoori spices",
        "serving_size": "1 roll (220g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "North Indian",
        "tags": "protein-rich,vegetarian,spicy,wrap",
        "image_emoji": "🌯",
        "calories": 310.0, "protein": 15.0, "carbohydrates": 34.0, "fat": 11.0,
        "fiber": 5.0, "sugar": 3.0, "sodium": 540.0
    },
    {
        "item_id": 38,
        "name": "Paneer Butter Masala Rice Bowl",
        "description": "Rich velvety cottage cheese cubes in aromatic tomato-cashew makhani gravy over steaming jeera basmati rice.",
        "category": "Rice",
        "price": 95.0,
        "ingredients": "paneer,basmati rice,butter,cream,tomato gravy,cashew,spices",
        "serving_size": "1 bowl (360g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": True,
        "spicy": False, "sweet": True,
        "preparation_time": 9, "available": True, "cuisine": "North Indian",
        "tags": "rich,makhani,creamy,comfort,indulgent",
        "image_emoji": "🍛",
        "calories": 520.0, "protein": 17.0, "carbohydrates": 68.0, "fat": 20.0,
        "fiber": 4.0, "sugar": 6.0, "sodium": 580.0
    },
    {
        "item_id": 39,
        "name": "Dal Makhani Rice Bowl",
        "description": "Slow-cooked creamy black lentils simmered overnight with butter and fresh cream, served with steamed basmati rice.",
        "category": "Rice",
        "price": 80.0,
        "ingredients": "black urad dal,kidney beans,basmati rice,butter,cream,spices",
        "serving_size": "1 bowl (350g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 7, "available": True, "cuisine": "North Indian",
        "tags": "slow-cooked,creamy,wholesome,classic,comfort",
        "image_emoji": "🍛",
        "calories": 480.0, "protein": 15.0, "carbohydrates": 64.0, "fat": 17.0,
        "fiber": 8.0, "sugar": 3.0, "sodium": 510.0
    },
    {
        "item_id": 40,
        "name": "Chicken Curry Rice Bowl",
        "description": "Homestyle slow-braised tender chicken curry infused with whole garam masala over fragrant basmati rice.",
        "category": "Rice",
        "price": 110.0,
        "ingredients": "tender chicken,basmati rice,onion gravy,ginger,garlic,spices",
        "serving_size": "1 bowl (360g)",
        "vegetarian": False, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 10, "available": True, "cuisine": "Indian",
        "tags": "non-veg,protein,spicy,satisfying,high-protein",
        "image_emoji": "🍗",
        "calories": 510.0, "protein": 28.0, "carbohydrates": 62.0, "fat": 16.0,
        "fiber": 4.0, "sugar": 3.0, "sodium": 650.0
    },
    {
        "item_id": 41,
        "name": "Mysore Masala Dosa",
        "description": "Extra-crispy fermented rice crepe smeared with fiery red garlic chutney and stuffed with spiced potato masala.",
        "category": "Snacks",
        "price": 75.0,
        "ingredients": "rice-lentil batter,spicy garlic red chutney,potato masala,sambar,coconut chutney",
        "serving_size": "1 dosa (220g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "South Indian",
        "tags": "crispy,spicy,garlic,traditional,breakfast",
        "image_emoji": "🥞",
        "calories": 380.0, "protein": 7.0, "carbohydrates": 56.0, "fat": 14.0,
        "fiber": 5.0, "sugar": 3.0, "sodium": 590.0
    },
    {
        "item_id": 42,
        "name": "Medu Vada Sambar (2 pcs)",
        "description": "Deep-fried golden savory lentil donuts, crispy outside and fluffy inside, served with hot sambar and fresh coconut dip.",
        "category": "Snacks",
        "price": 45.0,
        "ingredients": "urad dal,curry leaves,crushed black pepper,sambar,coconut chutney",
        "serving_size": "2 vadas (180g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": False,
        "preparation_time": 6, "available": True, "cuisine": "South Indian",
        "tags": "crispy,fluffy,savory,classic,breakfast",
        "image_emoji": "🍩",
        "calories": 310.0, "protein": 9.0, "carbohydrates": 38.0, "fat": 14.0,
        "fiber": 4.5, "sugar": 2.0, "sodium": 460.0
    },
    {
        "item_id": 43,
        "name": "Peri Peri French Fries",
        "description": "Golden crispy crinkle-cut potato fries dusted generously with zesty African bird's eye peri peri seasoning.",
        "category": "Snacks",
        "price": 55.0,
        "ingredients": "potatoes,peri peri spice mix,salt,oil",
        "serving_size": "1 basket (150g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 5, "available": True, "cuisine": "Continental",
        "tags": "crunchy,spicy,finger-food,fast,snack",
        "image_emoji": "🍟",
        "calories": 290.0, "protein": 4.0, "carbohydrates": 40.0, "fat": 13.0,
        "fiber": 3.5, "sugar": 1.0, "sodium": 490.0
    },
    {
        "item_id": 44,
        "name": "Bombay Masala Toast Sandwich",
        "description": "Triple-decker toasted sandwich packed with spiced turmeric potato mash, crunchy beetroot, onion rings, cucumber, and green chutney.",
        "category": "Snacks",
        "price": 55.0,
        "ingredients": "bread,potato masala,beetroot,onion,cheese,mint chutney,butter",
        "serving_size": "2 halves (200g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 6, "available": True, "cuisine": "Street Food",
        "tags": "toasted,spicy,vegetable-packed,cheesy,snack",
        "image_emoji": "🥪",
        "calories": 320.0, "protein": 8.0, "carbohydrates": 48.0, "fat": 11.0,
        "fiber": 4.0, "sugar": 4.0, "sodium": 520.0
    },
    {
        "item_id": 45,
        "name": "Chilli Garlic Noodles",
        "description": "Wok-charred wheat noodles tossed with pungent crushed garlic, dry red chili flakes, bell peppers, and scallions.",
        "category": "Noodles",
        "price": 75.0,
        "ingredients": "wheat noodles,crushed garlic,red chili flakes,capsicum,cabbage,soy sauce",
        "serving_size": "1 bowl (280g)",
        "vegetarian": True, "vegan": True, "jain": False,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 8, "available": True, "cuisine": "Indo-Chinese",
        "tags": "fiery,garlic,wok-tossed,spicy,noodles",
        "image_emoji": "🥢",
        "calories": 370.0, "protein": 8.0, "carbohydrates": 58.0, "fat": 12.0,
        "fiber": 4.0, "sugar": 3.0, "sodium": 640.0
    },
    {
        "item_id": 46,
        "name": "Peri Peri Maggi",
        "description": "Piping hot 2-minute canteen maggi noodles spiked with smoky fiery peri peri herbs, butter, and crunchy sweet corn.",
        "category": "Noodles",
        "price": 50.0,
        "ingredients": "maggi noodles,peri peri herbs,sweet corn,butter,tastemaker",
        "serving_size": "1 bowl (220g)",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": True, "sweet": False,
        "preparation_time": 7, "available": True, "cuisine": "Indian Fusion",
        "tags": "hot,cheesy-kick,canteen-style,spicy,maggi",
        "image_emoji": "🍜",
        "calories": 330.0, "protein": 7.0, "carbohydrates": 46.0, "fat": 13.0,
        "fiber": 3.0, "sugar": 3.0, "sodium": 590.0
    },
    {
        "item_id": 47,
        "name": "Oreo Chocolate Thick Shake",
        "description": "Creamy, indulgent whole milk shake blended with crunchy Oreo biscuits, vanilla ice cream, and Hershey's chocolate drizzle.",
        "category": "Beverages",
        "price": 65.0,
        "ingredients": "whole milk,oreo cookies,vanilla ice cream,chocolate syrup",
        "serving_size": "350 ml",
        "vegetarian": True, "vegan": False, "jain": False,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": True, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 4, "available": True, "cuisine": "Continental",
        "tags": "thick,sweet,rich,dessert-shake,cold",
        "image_emoji": "🥤",
        "calories": 390.0, "protein": 8.0, "carbohydrates": 54.0, "fat": 16.0,
        "fiber": 2.0, "sugar": 42.0, "sodium": 180.0
    },
    {
        "item_id": 48,
        "name": "Kesar Badam Milk (Chilled)",
        "description": "Refreshing traditional royal saffron-infused milk blended with ground almonds, green cardamom, and crushed pistachios.",
        "category": "Beverages",
        "price": 45.0,
        "ingredients": "milk,almonds,saffron (kesar),cardamom,pistachios,sugar",
        "serving_size": "250 ml",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": True,
        "spicy": False, "sweet": True,
        "preparation_time": 3, "available": True, "cuisine": "Indian",
        "tags": "royal,cooling,nuts,healthy,cold",
        "image_emoji": "🥛",
        "calories": 220.0, "protein": 9.0, "carbohydrates": 26.0, "fat": 9.0,
        "fiber": 2.5, "sugar": 22.0, "sodium": 95.0
    },
    {
        "item_id": 49,
        "name": "Lemon Iced Tea",
        "description": "Chilled black tea infused with fresh citrus lemon juice, cooling garden mint leaves, and light brown sugar over crushed ice.",
        "category": "Beverages",
        "price": 35.0,
        "ingredients": "brewed tea,fresh lemon juice,mint sprigs,sugar,crushed ice",
        "serving_size": "300 ml",
        "vegetarian": True, "vegan": True, "jain": True,
        "contains_egg": False, "contains_dairy": False, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 2, "available": True, "cuisine": "Continental",
        "tags": "refreshing,citrus,iced,summer,low-calorie",
        "image_emoji": "🍹",
        "calories": 90.0, "protein": 0.5, "carbohydrates": 22.0, "fat": 0.0,
        "fiber": 0.5, "sugar": 20.0, "sodium": 15.0
    },
    {
        "item_id": 50,
        "name": "Spongy Rasgulla (2 pcs)",
        "description": "Light, melt-in-mouth Kolkata-style cottage cheese spheres gently poached in fragrant rose and cardamom infused light sugar syrup.",
        "category": "Sweets",
        "price": 35.0,
        "ingredients": "chhena cottage cheese,sugar syrup,rose water,cardamom",
        "serving_size": "2 pcs (120g)",
        "vegetarian": True, "vegan": False, "jain": True,
        "contains_egg": False, "contains_dairy": True, "contains_gluten": False, "contains_nuts": False,
        "spicy": False, "sweet": True,
        "preparation_time": 2, "available": True, "cuisine": "Indian",
        "tags": "sweet,juicy,traditional,light,dessert",
        "image_emoji": "⚪",
        "calories": 180.0, "protein": 5.0, "carbohydrates": 38.0, "fat": 2.0,
        "fiber": 0.0, "sugar": 34.0, "sodium": 40.0
    }
]


FOOD_IMAGE_URLS = {
    "paneer kathi roll": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    "chicken tikka roll": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    "egg bhurji roll": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    "aloo corn roll": "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
    "soya chaap tikka roll": "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80",
    "veg biryani": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    "chicken dum biryani": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
    "rajma chawal": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    "jain dal khichdi": "https://images.unsplash.com/photo-1546833998-877b37c2e5c4?auto=format&fit=crop&w=800&q=80",
    "curd rice": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    "schezwan fried rice": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
    "paneer butter masala rice bowl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
    "dal makhani rice bowl": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    "chicken curry rice bowl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    "amritsari chole kulche": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    "cheese grilled sandwich": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    "bombay masala toast sandwich": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    "masala dosa": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
    "mysore masala dosa": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80",
    "samosa": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    "mumbai vada pav": "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
    "veg cutlet": "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80",
    "bun maska": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    "indori poha": "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80",
    "idli sambar": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    "medu vada sambar": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    "chole bhature": "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80",
    "mumbai pav bhaji": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80",
    "peri peri french fries": "https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80",
    "classic masala maggi": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
    "cheese masala maggi": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    "peri peri maggi": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
    "veg hakka noodles": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
    "egg hakka noodles": "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=800&q=80",
    "chilli garlic noodles": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
    "chilli paneer dry": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    "chilli chicken dry": "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    "cutting masala chai": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    "south indian filter coffee": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    "iced cold coffee": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80",
    "fresh lime soda": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "alphonso mango lassi": "https://images.unsplash.com/photo-1571006682875-a831e5055b88?auto=format&fit=crop&w=800&q=80",
    "chilled masala buttermilk": "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80",
    "oreo chocolate thick shake": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    "kesar badam milk": "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80",
    "lemon iced tea": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
    "warm gulab jamun": "https://images.unsplash.com/photo-1605197154344-934c56e3b5e0?auto=format&fit=crop&w=800&q=80",
    "chocolate walnut brownie": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    "fresh fruit custard": "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
    "spongy rasgulla": "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80",
}

_SORTED_KEYS = sorted(FOOD_IMAGE_URLS.keys(), key=lambda k: len(k), reverse=True)


def resolve_food_image_url(name: str) -> str:
    cleaned = re.sub(r'\([0-9]+\s*pcs\)', '', name, flags=re.IGNORECASE)
    cleaned = re.sub(r'\([a-z0-9/\s]+\)', '', cleaned, flags=re.IGNORECASE).strip().lower()
    for k in _SORTED_KEYS:
        if k in cleaned or k in name.lower():
            return FOOD_IMAGE_URLS[k]
    return "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80"


def seed_database():
    init_db()
    db = SessionLocal()

    # 1. Seed or update Food items
    print("Seeding/updating food items with nutrition data and verified images...")
    count = 0
    for data in FOOD_ITEMS:
        item_id = data["item_id"]
        # Set authentic image URL
        data["image_url"] = resolve_food_image_url(data["name"])
        existing = db.query(Food).filter(Food.item_id == item_id).first()
        if existing:
            for k, v in data.items():
                setattr(existing, k, v)
        else:
            db.add(Food(**data))
        count += 1
    db.commit()
    print(f"Seeded {count} food items successfully.")

    # 2. Seed Demo Student
    student_id = "student_lakshay"
    student = db.query(User).filter(User.id == student_id).first()
    if not student:
        student = User(
            id=student_id,
            name="Lakshay",
            email="student@example.com",
            password_hash="student123",
            role="student"
        )
        db.add(student)
        db.commit()

        # Seed profile
        profile = StudentProfile(
            user_id=student_id,
            budget=120.0,
            time_limit=10,
            mood="Comfort Food",
            cuisine_preference="Indian",
            dietary_preferences="Vegetarian",
            taste_preferences="Spicy"
        )
        db.add(profile)

        # Seed nutrition goals
        goals = StudentNutritionGoal(
            user_id=student_id,
            calorie_goal=2200.0,
            protein_goal=120.0,
            carb_goal=250.0,
            fat_goal=70.0,
            enabled=True
        )
        db.add(goals)
        db.commit()

        print(f"Created demo student account '{student.name}' with clean slate (no initial orders).")

    # 3. Seed Demo Owner
    owner_id = "owner_ramesh"
    owner = db.query(User).filter(User.id == owner_id).first()
    if not owner:
        owner = User(
            id=owner_id,
            name="Chef Ramesh",
            email="owner@canteen.edu",
            password_hash="owner123",
            role="cafeteria_owner",
            canteen_name="Campus Central Canteen",
            canteen_location="Student Activity Center, Block B",
            contact_info="+91 98765 43210"
        )
        db.add(owner)
        db.commit()
        print(f"Created demo owner account '{owner.name}'.")

    db.close()
    print("Database seeding finished!")


if __name__ == "__main__":
    seed_database()
